server {
    listen 80;
    listen [::]:80;
    server_name mirror.erised.click trans.erised.click;
    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/mirrised-acme;
    }

    location / {
        return 404;
    }
}

